version: "3"

services:
    php:
        container_name: cron_docker_php
        build:
            context: docker/php
            dockerfile: Dockerfile
        networks:
            - cron_docker_default
        environment:
            - APP_ENV=dev
        env_file:
            - ./env.dev
        volumes:
            - ./www:/var/www
            - ./docker/php/conf.d/custom-dev.ini:/usr/local/etc/php/conf.d/custom.ini

    nginx:
        container_name: cron_docker_nginx
        image: nginx
        networks:
            - cron_docker_default
        ports:
            - 8080:80
        volumes:
            - ./www:/var/www
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

networks:
    cron_docker_default:
